Repository 2011-team-yaya/grace-shopper, pull requests merged in 2021-01, with the labels that each got.

#24 feature: single product route, component, store, reducer, css
  client/components/AllProducts.js
  client/components/SingleProduct.js
  client/routes.js
  client/store/index.js
  client/store/singleProduct.js
  package-lock.json
  package.json
  public/style.css
  server/api/products.js
  server/db/models/user.js
Labels: enhancement

#25 feature: modified all-products images and added CSS for all-products …
  client/components/AllProducts.js
  package-lock.json
  package.json
  public/style.css
  server/db/db.js
Labels: enhancement

#26 Navbar feature: modified navbar, added css
  client/components/AllProducts.js
  client/components/navbar.js
  public/style.css
  server/db/db.js
Labels: enhancement

#29 fix(models)
  script/seed.js
  server/db/models/cart.js
  server/db/models/index.js
  server/db/models/order.js
  server/db/models/order_products.js
  server/db/models/user.js
Labels: bugfix

#31 fix(seed/models): refactored seed file
  client/components/AllProducts.js
  script/seed.js
  server/db/models/order.js
Labels: bugfix

#46 Cart component1
  client/components/AllProducts.js
  client/components/SingleProduct.js
  client/components/cart.js
  client/components/navbar.js
  client/store/cart.js
  client/store/index.js
  client/store/products.js
  package-lock.json
  package.json
  public/images/account.png
  public/images/cart.png
  public/images/logo.png
  public/style.css
  server/api/order_products.js
  server/auth/index.js
  server/index.js
Labels: bugfix, enhancement

#62 Edit cart
  client/components/SingleProduct.js
  client/components/cart.js
  client/components/navbar.js
  client/store/cart.js
  client/store/singleProduct.js
  server/api/order_products.js
Labels: bugfix, enhancement
